### ISSUE TITLE
Assert with error message?

### ISSUE THREAD

**Issue by Gekctek** [basvandijk/mops-test#2]
Is there way to run a test and have it print out details?
If i use Debug.trap, i get a message but its stop execution of the other tests
Do I just do and if statement, then Debug.print, then assert false?

**Comment by ZenVoich** [comment]
Hi.

If you want to just print something - `Debug.print`

If you want to "assert with message":
Instead of
```motoko
assert(x == y);
```

use this
```motoko
if (x != y) {
  Debug.trap("err x is not equal y");
};
```

And yes, if test traps(with `assert` or `Debug.trap`) current test file will stop execution.

**Comment by Gekctek** [comment]
Thanks!
