### ISSUE TITLE
Typo in Code Snippet in readme.md for expect.option Example

### ISSUE THREAD

**Issue by fenixbul** [basvandijk/mops-test#6]
I've noticed a small typo in the readme.md file, specifically in the code snippet provided for **expect.option**. The typo is in the variable name used in the example for an optional custom type. The variable is declared as "val", but later referenced as "v". This might cause confusion for users trying to understand or run the example code.

## `expect.option`
```motoko
  // ... previous code ...
  
  let val = ?{x = 1; y = 2};
  
  expect.option(v, showMyType, equalMyType).notEqual(null);
  expect.option(v, showMyType, equalMyType).isSome(); // != null
  expect.option(v, showMyType, equalMyType).equal(?{x = 1; y = 2});
```

**Comment by ZenVoich** [comment]
Thank you!

Fixed.
